<?php

namespace App\Helpers\Interfaces;

interface MailInterface
{
    //
    const STATUS_SENT = 'MAIL::STATUS::SENT';
    const STATUS_PENDING = 'MAIL::STATUS::PENDING';
    const STATUS_FAILED = 'MAIL::STATUS::FAILED';

    const TYPE_DEFAULT = "MAIL::CONTENT::HTML";
    const TYPE_CONTENT_TEXT = "MAIL::CONTENT::TEXT";
    const TYPE_CONTENT_HTML = "MAIL::CONTENT::HTML";
    const TYPE_CONTENT_LAYOUT = "MAIL::CONTENT::LAYOUT";

    const LAYOUT_BIRTHDAY_NORMAL = "MAIL::LAYOUT::BIRTHDAY::NORMAL";
    const LAYOUT_BIRTHDAY_CUSTOM = "MAIL::LAYOUT::BIRTHDAY::CUSTOM";

    const LAYOUT_BIRTHDAY_REMINDER_NORMAL = "MAIL::LAYOUT::BIRTHDAY::REMINDER::NORMAL";
    const LAYOUT_BIRTHDAY_REMINDER_CUSTOM = "MAIL::LAYOUT::BIRTHDAY::REMINDER::CUSTOM";

    const LAYOUT_CAMPAIGN_NORMAL = "MAIL::LAYOUT::CAMPAIGN::NORMAL";
    const LAYOUT_CAMPAIGN_CUSTOM = "MAIL::LAYOUT::CAMPAIGN::CUSTOM";
}
